//test response class

get http://localhost/php-api-todo/V1/model/test/responseTest.php

###

//testconnection bdd
get http://localhost/php-api-todo/V1/controller/test/Dbtest.php

###

//test Task php
get http://localhost/php-api-todo/V1/model/test/taskTest.php

###
//test Task php
get http://localhost/php-api-todo/tasks/task/4

###
//test Task php
PATCH   http://localhost/php-api-todo/tasks/task/1

###
//test Task php
DELETE http://localhost/php-api-todo/tasks/task/17

###

//test all tasks 
get http://localhost/php-api-todo/tasks/tasks

###

//get Task all complite or imcomplete
get http://localhost/php-api-todo/tasks/tasks/N

